services:
  - type: tcp
    name: socks5-proxy
    env: node
    plan: free
    buildCommand: ""
    startCommand: "bun run rend.ts"
    autoDeploy: true
    envVars:
      - key: PORT
        sync: false
